### ISSUE TITLE
har-validator error with npm install

### ISSUE THREAD

**Issue by CodeWithOz** [grommet/grommet-starter-new-app#4]
I kept getting a 404 error code with the message 
> Not Found: har-validator@5.1.2

when I ran `npm install`. I found [this discussion](https://github.com/ahmadnassri/node-har-validator/issues/113) about the issue and it seems there are mismatched version numbers in the npm/yarn repos for the `har-validator` package. I ended up using [this fix](https://github.com/ahmadnassri/node-har-validator/issues/113#issuecomment-438106000) but there are a number of others in that thread that could be used.

What would be an elegant solution for this problem in this repo? One option is to manually change the `package-lock.json` file like I did and commit the change. Another could be to mention the possibility of this error in the README, along with a link to that thread or something similar (so the dev knows about the different solutions available).

**Comment by Ranguro** [comment]
There are two paths two resolve this, one is only updating `har-validator` value in the `package-lock.json`. The other one is updating the `package-lock.json`. I will udpate the `package-lock.json` to fix the issue.
